name: Count Files and Folders

on:
  push:
  pull_request:

jobs:
  count:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Count files & folders
        run: |
          FILES=$(find . -type f | wc -l)
          DIRS=$(find . -type d | wc -l)

          echo "Total files: $FILES"
          echo "Total folders: $DIRS"
